# Copyright FUJITSU LIMITED 2015-2017.

tag_ServerType: ap

# appserver setting
tomcat_xms: 512m
tomcat_xmx: 512m
tomcat_metaspace_size: 256m
tomcat_max_metaspace_size: 256m

# lock / cache instance
lock_host: 127.0.0.1
lock_port: 11211
cache_host: 127.0.0.1
cache_port: 11212
# Type of cache manager. Either "memcached" or "none".
cache_manager: memcached


tomcat_version: 9.0.27
commons_daemon_version : 1.2.2
activemq_version: 5.15.8

# engine extensions
install_engine_extensions: yes
ex-ew-services_ver: 1.0.2
ex-httpclient_ver: 1.1.5
ex-mailsender_ver: 1.5.3
ex-slack_ver: 1.0.2
