# Copyright FUJITSU LIMITED 2015-2017.

- name: Deploy /etc/systemd/system/elasticsearch.service
  template: src=./resource/es/etc/systemd/system/elasticsearch.service dest=/etc/systemd/system/elasticsearch.service owner=root group=root mode=0755

- name: systemd reload
  command: systemctl daemon-reload

- name: Start elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: Deploy check_cluster_health.sh
  copy: src=./resource/es/personium/check_cluster_health.sh dest=/personium/check_cluster_health.sh owner=root group=root mode=0755

- name: exec check_cluster_health.sh
  command: /bin/bash /personium/check_cluster_health.sh {{base_url}}
