# Copyright FUJITSU LIMITED 2015-2017.

- name: Create /personium/personium-core/conf/token.key
  local_action: shell perl -le 'print map { ("a".."z", 0..9)[rand 36] } 1..16' > ./resource/ap/personium/personium-core/conf/token.key creates="./resource/ap/personium/personium-core/conf/token.key"
  run_once: true
  connection: local

- name: Deploy /personium/personium-core/conf/token.key
  copy: src=./resource/ap/personium/personium-core/conf/token.key dest=/personium/personium-core/conf/token.key owner=root group=root mode=0400

- name: Create /personium/personium-core/conf/salt.key
  local_action: shell perl -le 'print map { ("a".."z","A".."Z", 0..9)[rand 36] } 1..8' > ./resource/ap/personium/personium-core/conf/salt.key creates="./resource/ap/personium/personium-core/conf/salt.key"
  run_once: true
  connection: local

- name: Deploy /personium/personium-core/conf/salt.key
  copy: src=./resource/ap/personium/personium-core/conf/salt.key dest=/personium/personium-core/conf/salt.key owner=root group=root mode=0400

- name: Create /opt/x509 directory
  file: "state=directory path=/opt/x509 owner=personium group=personium mode=550"

- name: Deploy unit-self-sign.crt
  copy: src=./resource/ap/opt/x509/unit-self-sign.crt dest=/opt/x509/unit-self-sign.crt owner=personium group=personium mode=440

- name: Deploy unit.key
  copy: src=./resource/ap/opt/x509/unit.key dest=/opt/x509/unit.key owner=personium group=personium mode=440

- name: Create /opt/logback directory
  file: "state=directory path=/opt/logback owner=personium group=personium"
