# Copyright FUJITSU LIMITED 2015-2017.

- name: Get secret16
  command: cat /personium/personium-core/conf/token.key
  register: secret16

- name: Get salt
  command: cat /personium/personium-core/conf/salt.key
  register: salt

- name: Deploy personium-config.properties
  template: src=./resource/ap/personium/personium-core/conf/18888/personium-unit-config.properties.j2 dest=/personium/personium-core/conf/18888/personium-unit-config.properties owner=root group=root mode=0644

- name: Deploy logback.xml
  copy: src=./resource/ap/opt/logback/logback.xml dest=/opt/logback/logback.xml owner=personium group=personium mode=0644

- name: Create /personium/logback/log/logback.log
  file: path=/personium/logback/log/logback.log state=touch owner=personium group=personium mode=644

- name: Deploy /etc/logrotate.d/personium-core-log
  copy: src=./resource/ap/etc/logrotate.d/personium-core-log dest=/etc/logrotate.d/personium-core-log owner=root group=root mode=0644

- name: Stop tomcat
  systemd:
    name: tomcat
    state: stopped

- name: Delete /opt/tomcat/webapps/personium-core
  file: state=absent path=/opt/tomcat/webapps/personium-core

- name: Delete /opt/tomcat/webapps/personium-engine
  file: state=absent path=/opt/tomcat/webapps/personium-engine

- name: Deploy personium-core.war
  copy: src=./resource/ap/opt/tomcat/webapps/personium-core.war dest=/opt/tomcat/webapps/personium-core.war owner=personium group=personium mode=644

- name: Deploy personium-engine.war
  copy: src=./resource/ap/opt/tomcat/webapps/personium-engine.war dest=/opt/tomcat/webapps/personium-engine.war owner=personium group=personium mode=644

- name: Start tomcat
  systemd:
    name: tomcat
    state: started
