# Copyright FUJITSU LIMITED 2015-2017.

- name: Download logback
  command: wget -q -O logback-{{ logback_version }}.tar.gz --no-check-certificate http://logback.qos.ch/dist/logback-{{ logback_version }}.tar.gz
  args:
    chdir: /usr/local/src
    creates: /usr/local/src/logback-{{ logback_version }}.tar.gz

- name: Download slf4j
  command: wget -q -O slf4j-1.6.4.tar.gz --no-check-certificate http://www.slf4j.org/dist/slf4j-1.6.4.tar.gz
  args:
    chdir: /usr/local/src
    creates: /usr/local/src/slf4j-1.6.4.tar.gz

- name: Create /opt/logback directory
  file: state=directory path=/opt/logback owner=personium group=personium mode=0755

- name: Create /personium/logback/log/logback.log
  file: path=/personium/logback/log/logback.log state=touch owner=personium group=personium mode=644

- name: Expand logback
  command: tar xzf /usr/local/src/logback-{{ logback_version }}.tar.gz
  args:
    chdir: /opt/logback
    creates: /opt/logback/logback-{{ logback_version }}

- name: Expand slf4j
  command: tar xzf /usr/local/src/slf4j-1.6.4.tar.gz
  args:
    chdir: /opt/logback
    creates: /opt/logback/slf4j-1.6.4

- name: Change owner /opt/logback/logback-{{ logback_version }} directory
  file: state=directory path=/opt/logback/logback-{{ logback_version }} owner=personium group=personium recurse=yes

- name: Change owner /opt/logback/slf4j-1.6.4 directory
  file: state=directory path=/opt/logback/slf4j-1.6.4 owner=personium group=personium recurse=yes

- name: Deploy /etc/logrotate.d/personium-core-log
  copy: src=./resource/nfs/etc/logrotate.d/personium-core-log dest=/etc/logrotate.d/personium-core-log owner=root group=root mode=0644
