# Copyright FUJITSU LIMITED 2015-2017.

- name: /personium/personium-core を作成
  file: state=directory path=/personium/personium-core owner=personium group=personium mode=0755

- name: /personium/personium-core に /personium/personium-core/log を作成
  file: state=directory path=/personium/personium-core/log owner=personium group=personium mode=0755

- name: /personium/personium-core/conf を作成
  file: state=directory path=/personium/personium-core/conf owner=root group=root mode=0755

- name: /personium/personium-core/conf/18888 を作成
  file: state=directory path=/personium/personium-core/conf/18888 owner=root group=root mode=0755

- name: /personium/personium-core/conf/28888 を作成
  file: state=directory path=/personium/personium-core/conf/28888 owner=root group=root mode=0755

- name: /personium/personium-core/conf/38888 を作成
  file: state=directory path=/personium/personium-core/conf/38888 owner=root group=root mode=0755

- name: /personium/personium-core/conf/48888 を作成
  file: state=directory path=/personium/personium-core/conf/48888 owner=root group=root mode=0755

- name: /personium/personium-core/ads を作成
  file: state=directory path=/personium/personium-core/ads owner=personium group=personium mode=0755

- name: /personium/personium-core/plugins を作成
  file: state=directory path=/personium/personium-core/plugins owner=personium group=personium mode=0755

- name: /personium/personium-engine を作成
  file: state=directory path=/personium/personium-engine owner=personium group=personium mode=0755

- name: /personium/personium-engine/log を作成
  file: state=directory path=/personium/personium-engine/log owner=personium group=personium mode=0755

- name: /personium/personium-engine/extensions を作成
  file: state=directory path=/personium/personium-engine/extensions owner=personium group=personium mode=0755

- name: /personium/personium を作成
  file: state=directory path=/opt/ap_piolog/personium owner=personium group=personium mode=0755

- name: /personium/personium/log を作成
  file: state=directory path=/opt/ap_piolog/personium/log owner=personium group=personium mode=0755

- name: /personium/18888 を作成
  file: state=directory path=/personium/18888 owner=personium group=personium mode=0755

- name: /personium/18888/personium-engine を作成
  file: state=directory path=/personium/18888/personium-engine owner=personium group=personium mode=0755

- name: /personium/18888/personium-engine/extensions を作成
  file: state=directory path=/personium/18888/personium-engine/extensions owner=personium group=personium mode=0755

- name: /personium/28888 を作成
  file: state=directory path=/personium/28888 owner=personium group=personium mode=0755

- name: /personium/28888/personium-engine を作成
  file: state=directory path=/personium/28888/personium-engine owner=personium group=personium mode=0755

- name: /personium/28888/personium-engine/extensions を作成
  file: state=directory path=/personium/28888/personium-engine/extensions owner=personium group=personium mode=0755

- name: /personium/38888 を作成
  file: state=directory path=/personium/38888 owner=personium group=personium mode=0755

- name: /personium/38888/personium-engine を作成
  file: state=directory path=/personium/38888/personium-engine owner=personium group=personium mode=0755

- name: /personium/38888/personium-engine/extensions を作成
  file: state=directory path=/personium/38888/personium-engine/extensions owner=personium group=personium mode=0755

- name: /personium/48888 を作成
  file: state=directory path=/personium/48888 owner=personium group=personium mode=0755

- name: /personium/48888/personium-engine を作成
  file: state=directory path=/personium/48888/personium-engine owner=personium group=personium mode=0755

- name: /personium/48888/personium-engine/extensions を作成
  file: state=directory path=/personium/48888/personium-engine/extensions owner=personium group=personium mode=0755

- name: /personium_nfs を作成
  file: state=directory path=/personium_nfs owner=root group=root mode=0755

- name: /personium_nfs/personium-core を作成
  file: state=directory path=/personium_nfs/personium-core owner=personium group=personium mode=0755

- name: /personium_nfs/personium-core/dav を作成
  file: path=/opt/nfs1/personium-core/dav state=directory owner=personium group=personium mode=0777

- name: /personium_nfs/personium-core/eventlog を作成
  file: path=/opt/nfs1/personium-core/eventlog state=directory owner=personium group=personium mode=0777

- name: /personium_nfs/personium-core/barInstall を作成
  file: path=/opt/nfs1/personium-core/barInstall state=directory owner=personium group=personium mode=0777
